### ISSUE TITLE
Do you can give this library without composer?

### ISSUE THREAD

**Issue by Raserad** [meertensm/DPD#2]
Why do you shove this damn composer into any project? Can you work without it? I'm fed to the teeth see this composer in any project of php... So, please give me a project without composer. If you can. But i see what do you really use composer just for 3 files? 3 files Carl!

**Comment by pmingram** [comment]
@Raserad I imagine the author wanted to take advantage of PSR-4, or the 3 files are in multiple projects and thus using Composer makes it much easier to handle updates than trying to remember which ones you have updated the specific files in.

Of course, that doesn't mean you need to use Composer. There should be absolutely nothing stopping you from taking the 3 files from this repo, putting them into your codebase, including said files manually and continuing on your way.

**Comment by ollieread** [comment]
@Raserad composer is a PHP package manager, you should look it up. It's super beneficial and makes life easier.

Pro tip: You can download the code here https://github.com/meertensm/DPD/releases

**Comment by Raserad** [comment]
Thanks all for help me)))
